# Generated by Django 3.0.5 on 2020-04-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
